site_name: PySide6 Compact Documentation

theme:
  name: material
  favicon: favicon.ico
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - navigation.tabs
    - navigation.footer
    - navigation.sections

extra:
  collapse_toc: true
  disable_nav_previous_next: true


plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: "source"

markdown_extensions:
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_css:
  - assets/hl_color.css

nav:
  - Home: index.md
  - Installation Guide: Installation_Guide.md
  - Tutorial: 
    - Introduction: tutorial/index.md
    - 1. Creating a simple window: tutorial/creating_a_simple_window.md
    - 2. Adding widgets to a window: tutorial/adding_widgets_to_a_window.md
    - 3. Connecting widgets to a function: tutorial/connecting_widgets_to_a_function.md
    - Next Steps: tutorial/next_steps.md
  - API Reference: 
    - Overview: QtWidgets/index.md
    - QtWidgets/QApplication.md
    - QtWidgets/QMainWindow.md
    - QtWidgets/QLayout.md
    - QtWidgets/QWidget.md

    - QLayouts:
      - QtWidgets/QHBoxLayout.md
      - QtWidgets/QVBoxLayout.md
      - QtWidgets/QGroupBox.md
    - QWidgets:
      - QtWidgets/QTextEdit.md
      - QtWidgets/QCheckBox.md
      - QtWidgets/QLabel.md
      - QtWidgets/QComboBox.md
      - QtWidgets/QSpinBox.md
      - QtWidgets/QDoubleSpinBox.md
      - QtWidgets/QPushButton.md
  