site_name: PySide6 Compact Documentation

theme:
  name: null
  custom_dir: 'docs/cinder'
  site_favicon: favicon.ico
  disable_nav_previous_next: true
  features: 
    - content.code.copy
    - content.code.select

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: "source"

markdown_extensions:
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


nav:
  - index.md
  - User_Guide.md
  - API_reference.md
