site_name: PySide6 Compact Documentation

theme:
  name: material
  features:
    - content.code.copy
    - navigation.expand
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - navigation.tabs


extra:
  collapse_toc: true
  disable_nav_previous_next: true


plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: "source"

markdown_extensions:
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


nav:
  - Home: index.md
  - User Guide: User_Guide.md
  - API Reference:
    - Overview: PyQtWidgets/index.md
    - PyQtWidgets:
        - PyQtWidgets/QMainWindow.md
        - PyQtWidgets/QHBoxLayout.md
        - PyQtWidgets/QVBoxLayout.md
        - PyQtWidgets/QGroupBox.md
        - PyQtWidgets/QTextEdit.md
        - PyQtWidgets/QCheckBox.md
        - PyQtWidgets/QLabel.md
        - PyQtWidgets/QComboBox.md
        - PyQtWidgets/QSpinBox.md
        - PyQtWidgets/QDoubleSpinBox.md
        - PyQtWidgets/QPushButton.md
   