site_name: PySide6 Compact Documentation

theme:
  name: null
  custom_dir: 'docs/cinder'
  logo: figures/ECPC_logo_plain.svg
  favicon: figures/ECPC_logo_simple.svg

plugins:
  - search
  - macros

nav:
  - index.md
