site_name: PySide6 Compact Documentation

theme:
  name: null
  custom_dir: 'docs/cinder'
  logo: favicon.ico
  site_favicon: favicon.ico
  disable_nav_previous_next: true

plugins:
  - search
  - mkdocstrings

nav:
  - index.md
  - User_Guide.md
  - API_reference.md
