site_name: PySide6 Compact Documentation

theme:
  name: material
  favicon: favicon.ico
  features:
    - content.code.copy
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - navigation.tabs


extra:
  collapse_toc: true
  disable_nav_previous_next: true


plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: "source"

markdown_extensions:
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


nav:
  - Home: index.md
  - Installation Guide: Installation_Guide.md
  - Tutorial: tutorial.md
  - API Reference:
    - Overview: QtWidgets/index.md
    - QtWidgets:
        - QtWidgets/QApplication.md
        - QtWidgets/QMainWindow.md
        - QtWidgets/QHBoxLayout.md
        - QtWidgets/QVBoxLayout.md
        - QtWidgets/QGroupBox.md
        - QtWidgets/QTextEdit.md
        - QtWidgets/QCheckBox.md
        - QtWidgets/QLabel.md
        - QtWidgets/QComboBox.md
        - QtWidgets/QSpinBox.md
        - QtWidgets/QDoubleSpinBox.md
        - QtWidgets/QPushButton.md
   