"""
This page contains the API documentation of a compact version of the **PySide6.QtWidgets** module. 
"""

# Module `PySide6.QtWidgets`

import PySide6.QtWidgets
import PySide6.QtCore
import PySide6.QtGui

import enum
from typing import (
    Any,
    ClassVar,
    Dict,
    Iterable,
    List,
    Optional,
    Sequence,
    Text,
    Tuple,
    Type,
    Union,
    overload,
)
from PySide6.QtCore import Signal, SignalInstance
from shiboken6 import Shiboken

NoneType = type(None)


class QMainWindow:
    """
    A main window provides a framework for building an application's user interface.
    A user interface has to have one main window. QMainWindow provides a main
    application window. To the main window you can add other layouts, such as
    QHBoxLayout and QVBoxLayout.

    Examples:
        ``` py
        window = QMainWindow()
        ```
    """

    # iconSizeChanged          : ClassVar[Signal] = ... # iconSizeChanged(QSize)
    # tabifiedDockWidgetActivated: ClassVar[Signal] = ... # tabifiedDockWidgetActivated(QDockWidget*)
    # toolButtonStyleChanged   : ClassVar[Signal] = ... # toolButtonStyleChanged(Qt::ToolButtonStyle)

    # class DockOption(enum.Flag):

    #     AnimatedDocks            : QMainWindow.DockOption = ... # 0x1
    #     AllowNestedDocks         : QMainWindow.DockOption = ... # 0x2
    #     AllowTabbedDocks         : QMainWindow.DockOption = ... # 0x4
    #     ForceTabbedDocks         : QMainWindow.DockOption = ... # 0x8
    #     VerticalTabs             : QMainWindow.DockOption = ... # 0x10
    #     GroupedDragging          : QMainWindow.DockOption = ... # 0x20

    # def __init__(self, parent: Optional[PySide6.QtWidgets.QWidget] = ..., flags: PySide6.QtCore.Qt.WindowType = ...) -> None: ...

    # @overload
    # def addDockWidget(self, area: PySide6.QtCore.Qt.DockWidgetArea, dockwidget: PySide6.QtWidgets.QDockWidget) -> None: ...
    # @overload
    # def addDockWidget(self, area: PySide6.QtCore.Qt.DockWidgetArea, dockwidget: PySide6.QtWidgets.QDockWidget, orientation: PySide6.QtCore.Qt.Orientation) -> None: ...
    # @overload
    # def addToolBar(self, area: PySide6.QtCore.Qt.ToolBarArea, toolbar: PySide6.QtWidgets.QToolBar) -> None: ...
    # @overload
    # def addToolBar(self, title: str) -> PySide6.QtWidgets.QToolBar: ...
    # @overload
    # def addToolBar(self, toolbar: PySide6.QtWidgets.QToolBar) -> None: ...
    # def addToolBarBreak(self, area: PySide6.QtCore.Qt.ToolBarArea = ...) -> None: ...
    # def centralWidget(self) -> PySide6.QtWidgets.QWidget: ...
    # def contextMenuEvent(self, event: PySide6.QtGui.QContextMenuEvent) -> None: ...
    # def corner(self, corner: PySide6.QtCore.Qt.Corner) -> PySide6.QtCore.Qt.DockWidgetArea: ...
    # def createPopupMenu(self) -> PySide6.QtWidgets.QMenu: ...
    # def dockOptions(self) -> PySide6.QtWidgets.QMainWindow.DockOption: ...
    # def dockWidgetArea(self, dockwidget: PySide6.QtWidgets.QDockWidget) -> PySide6.QtCore.Qt.DockWidgetArea: ...
    # def documentMode(self) -> bool: ...
    # def event(self, event: PySide6.QtCore.QEvent) -> bool: ...
    # def iconSize(self) -> PySide6.QtCore.QSize: ...
    # def insertToolBar(self, before: PySide6.QtWidgets.QToolBar, toolbar: PySide6.QtWidgets.QToolBar) -> None: ...
    # def insertToolBarBreak(self, before: PySide6.QtWidgets.QToolBar) -> None: ...
    # def isAnimated(self) -> bool: ...
    # def isDockNestingEnabled(self) -> bool: ...
    # def isSeparator(self, pos: PySide6.QtCore.QPoint) -> bool: ...
    # def menuBar(self) -> PySide6.QtWidgets.QMenuBar: ...
    # def menuWidget(self) -> PySide6.QtWidgets.QWidget: ...
    # def removeDockWidget(self, dockwidget: PySide6.QtWidgets.QDockWidget) -> None: ...
    # def removeToolBar(self, toolbar: PySide6.QtWidgets.QToolBar) -> None: ...
    # def removeToolBarBreak(self, before: PySide6.QtWidgets.QToolBar) -> None: ...
    # def resizeDocks(self, docks: Sequence[PySide6.QtWidgets.QDockWidget], sizes: Sequence[int], orientation: PySide6.QtCore.Qt.Orientation) -> None: ...
    # def restoreDockWidget(self, dockwidget: PySide6.QtWidgets.QDockWidget) -> bool: ...
    # def restoreState(self, state: Union[PySide6.QtCore.QByteArray, bytes], version: int = ...) -> bool: ...
    # def saveState(self, version: int = ...) -> PySide6.QtCore.QByteArray: ...
    # def setAnimated(self, enabled: bool) -> None: ...
    # def setCentralWidget(self, widget: PySide6.QtWidgets.QWidget) -> None: ...
    # def setCorner(self, corner: PySide6.QtCore.Qt.Corner, area: PySide6.QtCore.Qt.DockWidgetArea) -> None: ...
    # def setDockNestingEnabled(self, enabled: bool) -> None: ...
    # def setDockOptions(self, options: PySide6.QtWidgets.QMainWindow.DockOption) -> None: ...
    # def setDocumentMode(self, enabled: bool) -> None: ...
    # def setIconSize(self, iconSize: PySide6.QtCore.QSize) -> None: ...
    # def setMenuBar(self, menubar: PySide6.QtWidgets.QMenuBar) -> None: ...
    # def setMenuWidget(self, menubar: PySide6.QtWidgets.QWidget) -> None: ...
    # def setStatusBar(self, statusbar: PySide6.QtWidgets.QStatusBar) -> None: ...
    # def setTabPosition(self, areas: PySide6.QtCore.Qt.DockWidgetArea, tabPosition: PySide6.QtWidgets.QTabWidget.TabPosition) -> None: ...
    # def setTabShape(s_summary_elf, tabShape: PySide6.QtWidgets.QTabWidget.TabShape) -> None: ...
    # def setToolButtonStyle(self, toolButtonStyle: PySide6.QtCore.Qt.ToolButtonStyle) -> None: ...
    # def setUnifiedTitleAndToolBarOnMac(self, set: bool) -> None: ...
    # def splitDockWidget(self, after: PySide6.QtWidgets.QDockWidget, dockwidget: PySide6.QtWidgets.QDockWidget, orientation: PySide6.QtCore.Qt.Orientation) -> None: ...
    # def statusBar(self) -> PySide6.QtWidgets.QStatusBar: ...
    # def tabPosition(self, area: PySide6.QtCore.Qt.DockWidgetArea) -> PySide6.QtWidgets.QTabWidget.TabPosition: ...
    # def tabShape(self) -> PySide6.QtWidgets.QTabWidget.TabShape: ...
    # def tabifiedDockWidgets(self, dockwidget: PySide6.QtWidgets.QDockWidget) -> List[PySide6.QtWidgets.QDockWidget]: ...
    # def tabifyDockWidget(self, first: PySide6.QtWidgets.QDockWidget, second: PySide6.QtWidgets.QDockWidget) -> None: ...
    # def takeCentralWidget(self) -> PySide6.QtWidgets.QWidget: ...
    # def toolBarArea(self, toolbar: PySide6.QtWidgets.QToolBar) -> PySide6.QtCore.Qt.ToolBarArea: ...
    # def toolBarBreak(self, toolbar: PySide6.QtWidgets.QToolBar) -> bool: ...
    # def toolButtonStyle(self) -> PySide6.QtCore.Qt.ToolButtonStyle: ...
    # def unifiedTitleAndToolBarOnMac(self) -> bool: ...


class QHBoxLayout:
    """
    The QHBoxLayout class lines up widgets horizontally. If the widgets do not fit
    in the window, the layout will automatically wrap or resize them.

    Examples:
        ``` py
        layout = QHBoxLayout()
        layout.addWidget(QPushButton("Button 1"))
        layout.addWidget(QPushButton("Button 2"))
        ```

        ``` py
        layout = QHBoxLayout()
        layout.addLayout(QVBoxLayout())
        ```
    """

    def addLayout(self, layout: PySide6.QtWidgets.QBoxLayout) -> None:
        """Adds a layout to the horizontal box layout

        Args:
            Layout (PySide6.QtWidgets.QBoxLayout): Layout
        """

    def addWidget(self, widget: PySide6.QtWidgets.QWidget) -> None:
        """Adds a widget to the horizontal box layout

        Args:
            widget (PySide6.QtWidgets.QWidget): Widget
        """

    # @overload
    # def __init__(self) -> None: ...
    # @overload
    # def __init__(self, parent: PySide6.QtWidgets.QWidget) -> None: ...


class QVBoxLayout:
    """
    The QVBoxLayout class lines up widgets vertically. If the widgets do not fit
    in the window, the layout will automatically wrap or resize them.

    examples:
        ``` py
        vbox = QVBoxLayout()
        textedit = QTextEdit()
        vbox.addWidget(textedit)
        ```
        ``` py
        vbox = QVBoxLayout()
        hbox = QHBoxLayout()
        vbox.addLayout(hbox)
        ```
    """

    def addLayout(self, layout: PySide6.QtWidgets.QBoxLayout) -> None:
        """Adds a layout to the vertical box layout

        Args:
            Layout (PySide6.QtWidgets.QBoxLayout): Layout
        """

    def addWidget(self, widget: PySide6.QtWidgets.QWidget) -> None:
        """Adds a widget to the vertical box layout

        Args:
            widget (PySide6.QtWidgets.QWidget): Widget
        """

    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, parent: PySide6.QtWidgets.QWidget) -> None: ...


class QFormLayout:
    """_summary_"""

    class FieldGrowthPolicy(enum.Enum):

        FieldsStayAtSizeHint: QFormLayout.FieldGrowthPolicy = ...  # 0x0
        ExpandingFieldsGrow: QFormLayout.FieldGrowthPolicy = ...  # 0x1
        AllNonFixedFieldsGrow: QFormLayout.FieldGrowthPolicy = ...  # 0x2

    class ItemRole(enum.Enum):

        LabelRole: QFormLayout.ItemRole = ...  # 0x0
        FieldRole: QFormLayout.ItemRole = ...  # 0x1
        SpanningRole: QFormLayout.ItemRole = ...  # 0x2

    class RowWrapPolicy(enum.Enum):

        DontWrapRows: QFormLayout.RowWrapPolicy = ...  # 0x0
        WrapLongRows: QFormLayout.RowWrapPolicy = ...  # 0x1
        WrapAllRows: QFormLayout.RowWrapPolicy = ...  # 0x2

    class TakeRowResult(Shiboken.Object):
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(
            self, TakeRowResult: PySide6.QtWidgets.QFormLayout.TakeRowResult
        ) -> None: ...
        @staticmethod
        def __copy__() -> None: ...

    def __init__(self, parent: Optional[PySide6.QtWidgets.QWidget] = ...) -> None: ...
    def addItem(self, item: PySide6.QtWidgets.QLayoutItem) -> None: ...
    @overload
    def addRow(
        self, label: PySide6.QtWidgets.QWidget, field: PySide6.QtWidgets.QLayout
    ) -> None: ...
    @overload
    def addRow(
        self, label: PySide6.QtWidgets.QWidget, field: PySide6.QtWidgets.QWidget
    ) -> None: ...
    @overload
    def addRow(self, labelText: str, field: PySide6.QtWidgets.QLayout) -> None: ...
    @overload
    def addRow(self, labelText: str, field: PySide6.QtWidgets.QWidget) -> None: ...
    @overload
    def addRow(self, layout: PySide6.QtWidgets.QLayout) -> None: ...
    @overload
    def addRow(self, widget: PySide6.QtWidgets.QWidget) -> None: ...

    # def count(self) -> int: ...
    # def expandingDirections(self) -> PySide6.QtCore.Qt.Orientation: ...
    # def fieldGrowthPolicy(self) -> PySide6.QtWidgets.QFormLayout.FieldGrowthPolicy: ...
    # def formAlignment(self) -> PySide6.QtCore.Qt.AlignmentFlag: ...
    # def getItemPosition(self, index: int) -> object: ...
    # def getLayoutPosition(self, layout: PySide6.QtWidgets.QLayout) -> object: ...
    # def getWidgetPosition(self, widget: PySide6.QtWidgets.QWidget) -> object: ...
    # def hasHeightForWidth(self) -> bool: ...
    # def heightForWidth(self, width: int) -> int: ...
    # def horizontalSpacing(self) -> int: ...
    # @overload
    # def insertRow(self, row: int, label: PySide6.QtWidgets.QWidget, field: PySide6.QtWidgets.QLayout) -> None: ...
    # @overload
    # def insertRow(self, row: int, label: PySide6.QtWidgets.QWidget, field: PySide6.QtWidgets.QWidget) -> None: ...
    # @overload
    # def insertRow(self, row: int, labelText: str, field: PySide6.QtWidgets.QLayout) -> None: ...
    # @overload
    # def insertRow(self, row: int, labelText: str, field: PySide6.QtWidgets.QWidget) -> None: ...
    # @overload
    # def insertRow(self, row: int, layout: PySide6.QtWidgets.QLayout) -> None: ...
    # @overload
    # def insertRow(self, row: int, widget: PySide6.QtWidgets.QWidget) -> None: ...
    # def invalidate(self) -> None: ...
    # @overload
    # def isRowVisible(self, layout: PySide6.QtWidgets.QLayout) -> bool: ...
    # @overload
    # def isRowVisible(self, row: int) -> bool: ...
    # @overload
    # def isRowVisible(self, widget: PySide6.QtWidgets.QWidget) -> bool: ...
    # @overload
    # def itemAt(self, index: int) -> PySide6.QtWidgets.QLayoutItem: ...
    # @overload
    # def itemAt(self, row: int, role: PySide6.QtWidgets.QFormLayout.ItemRole) -> PySide6.QtWidgets.QLayoutItem: ...
    # def labelAlignment(self) -> PySide6.QtCore.Qt.AlignmentFlag: ...
    # @overload
    # def labelForField(self, field: PySide6.QtWidgets.QLayout) -> PySide6.QtWidgets.QWidget: ...
    # @overload
    # def labelForField(self, field: PySide6.QtWidgets.QWidget) -> PySide6.QtWidgets.QWidget: ...
    # def minimumSize(self) -> PySide6.QtCore.QSize: ...
    # @overload
    # def removeRow(self, layout: PySide6.QtWidgets.QLayout) -> None: ...
    # @overload
    # def removeRow(self, row: int) -> None: ...
    # @overload
    # def removeRow(self, widget: PySide6.QtWidgets.QWidget) -> None: ...
    # def rowCount(self) -> int: ...
    # def rowWrapPolicy(self) -> PySide6.QtWidgets.QFormLayout.RowWrapPolicy: ...
    # def setFieldGrowthPolicy(self, policy: PySide6.QtWidgets.QFormLayout.FieldGrowthPolicy) -> None: ...
    # def setFormAlignment(self, alignment: PySide6.QtCore.Qt.AlignmentFlag) -> None: ...
    # def setGeometry(self, rect: PySide6.QtCore.QRect) -> None: ...
    # def setHorizontalSpacing(self, spacing: int) -> None: ...
    # def setItem(self, row: int, role: PySide6.QtWidgets.QFormLayout.ItemRole, item: PySide6.QtWidgets.QLayoutItem) -> None: ...
    # def setLabelAlignment(self, alignment: PySide6.QtCore.Qt.AlignmentFlag) -> None: ...
    # def setLayout(self, row: int, role: PySide6.QtWidgets.QFormLayout.ItemRole, layout: PySide6.QtWidgets.QLayout) -> None: ...
    # @overload
    # def setRowVisible(self, layout: PySide6.QtWidgets.QLayout, on: bool) -> None: ...
    # @overload
    # def setRowVisible(self, row: int, on: bool) -> None: ...
    # @overload
    # def setRowVisible(self, widget: PySide6.QtWidgets.QWidget, on: bool) -> None: ...
    # def setRowWrapPolicy(self, policy: PySide6.QtWidgets.QFormLayout.RowWrapPolicy) -> None: ...
    # def setSpacing(self, arg__1: int) -> None: ...
    # def setVerticalSpacing(self, spacing: int) -> None: ...
    # def setWidget(self, row: int, role: PySide6.QtWidgets.QFormLayout.ItemRole, widget: PySide6.QtWidgets.QWidget) -> None: ...
    # def sizeHint(self) -> PySide6.QtCore.QSize: ...
    # def spacing(self) -> int: ...
    # def takeAt(self, index: int) -> PySide6.QtWidgets.QLayoutItem: ...
    # @overload
    # def takeRow(self, layout: PySide6.QtWidgets.QLayout) -> PySide6.QtWidgets.QFormLayout.TakeRowResult: ...
    # @overload
    # def takeRow(self, row: int) -> PySide6.QtWidgets.QFormLayout.TakeRowResult: ...
    # @overload
    # def takeRow(self, widget: PySide6.QtWidgets.QWidget) -> PySide6.QtWidgets.QFormLayout.TakeRowResult: ...
    # def verticalSpacing(self) -> int: ...


class QGroupBox:
    """_summary_

    Args:
        PySide6 (_type_): _description_
    """

    ...
    # clicked                  : ClassVar[Signal] = ... # clicked()
    # toggled                  : ClassVar[Signal] = ... # toggled(bool)

    # @overload
    # def __init__(self, parent: Optional[PySide6.QtWidgets.QWidget] = ...) -> None: ...
    # @overload
    # def __init__(self, title: str, parent: Optional[PySide6.QtWidgets.QWidget] = ...) -> None: ...

    # def alignment(self) -> PySide6.QtCore.Qt.AlignmentFlag: ...
    # def changeEvent(self, event: PySide6.QtCore.QEvent) -> None: ...
    # def childEvent(self, event: PySide6.QtCore.QChildEvent) -> None: ...
    # def event(self, event: PySide6.QtCore.QEvent) -> bool: ...
    # def focusInEvent(self, event: PySide6.QtGui.QFocusEvent) -> None: ...
    # def initStyleOption(self, option: PySide6.QtWidgets.QStyleOptionGroupBox) -> None: ...
    # def isCheckable(self) -> bool: ...
    # def isChecked(self) -> bool: ...
    # def isFlat(self) -> bool: ...
    # def minimumSizeHint(self) -> PySide6.QtCore.QSize: ...
    # def mouseMoveEvent(self, event: PySide6.QtGui.QMouseEvent) -> None: ...
    # def mousePressEvent(self, event: PySide6.QtGui.QMouseEvent) -> None: ...
    # def mouseReleaseEvent(self, event: PySide6.QtGui.QMouseEvent) -> None: ...
    # def paintEvent(self, event: PySide6.QtGui.QPaintEvent) -> None: ...
    # def resizeEvent(self, event: PySide6.QtGui.QResizeEvent) -> None: ...
    # def setAlignment(self, alignment: int) -> None: ...
    # def setCheckable(self, checkable: bool) -> None: ...
    # def setChecked(self, checked: bool) -> None: ...
    # def setFlat(self, flat: bool) -> None: ...
    # def setTitle(self, title: str) -> None: ...
    # def title(self) -> str: ...


class QTextEdit:
    """_summary_

    Args:
        PySide6 (_type_): _description_
    """

    copyAvailable: ClassVar[Signal] = ...  # copyAvailable(bool)
    currentCharFormatChanged: ClassVar[Signal] = (
        ...
    )  # currentCharFormatChanged(QTextCharFormat)
    cursorPositionChanged: ClassVar[Signal] = ...  # cursorPositionChanged()
    redoAvailable: ClassVar[Signal] = ...  # redoAvailable(bool)
    selectionChanged: ClassVar[Signal] = ...  # selectionChanged()
    textChanged: ClassVar[Signal] = ...  # textChanged()
    undoAvailable: ClassVar[Signal] = ...  # undoAvailable(bool)

    class AutoFormattingFlag(enum.Flag):

        AutoAll: QTextEdit.AutoFormattingFlag = ...  # -0x1
        AutoNone: QTextEdit.AutoFormattingFlag = ...  # 0x0
        AutoBulletList: QTextEdit.AutoFormattingFlag = ...  # 0x1

    class ExtraSelection(Shiboken.Object):
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(
            self, ExtraSelection: PySide6.QtWidgets.QTextEdit.ExtraSelection
        ) -> None: ...
        @staticmethod
        def __copy__() -> None: ...

    class LineWrapMode(enum.Enum):

        NoWrap: QTextEdit.LineWrapMode = ...  # 0x0
        WidgetWidth: QTextEdit.LineWrapMode = ...  # 0x1
        FixedPixelWidth: QTextEdit.LineWrapMode = ...  # 0x2
        FixedColumnWidth: QTextEdit.LineWrapMode = ...  # 0x3

    @overload
    def __init__(self, parent: Optional[PySide6.QtWidgets.QWidget] = ...) -> None: ...
    @overload
    def __init__(
        self, text: str, parent: Optional[PySide6.QtWidgets.QWidget] = ...
    ) -> None: ...
    def acceptRichText(self) -> bool: ...
    def alignment(self) -> PySide6.QtCore.Qt.AlignmentFlag: ...
    def anchorAt(self, pos: PySide6.QtCore.QPoint) -> str: ...
    def append(self, text: str) -> None: ...
    def autoFormatting(self) -> PySide6.QtWidgets.QTextEdit.AutoFormattingFlag: ...
    def canInsertFromMimeData(self, source: PySide6.QtCore.QMimeData) -> bool: ...
    def canPaste(self) -> bool: ...
    def changeEvent(self, e: PySide6.QtCore.QEvent) -> None: ...
    def clear(self) -> None: ...
    def contextMenuEvent(self, e: PySide6.QtGui.QContextMenuEvent) -> None: ...
    def copy(self) -> None: ...
    def createMimeDataFromSelection(self) -> PySide6.QtCore.QMimeData: ...
    @overload
    def createStandardContextMenu(self) -> PySide6.QtWidgets.QMenu: ...
    @overload
    def createStandardContextMenu(
        self, position: PySide6.QtCore.QPoint
    ) -> PySide6.QtWidgets.QMenu: ...
    def currentCharFormat(self) -> PySide6.QtGui.QTextCharFormat: ...
    def currentFont(self) -> PySide6.QtGui.QFont: ...
    def cursorForPosition(
        self, pos: PySide6.QtCore.QPoint
    ) -> PySide6.QtGui.QTextCursor: ...
    @overload
    def cursorRect(self) -> PySide6.QtCore.QRect: ...
    @overload
    def cursorRect(self, cursor: PySide6.QtGui.QTextCursor) -> PySide6.QtCore.QRect: ...
    def cursorWidth(self) -> int: ...
    def cut(self) -> None: ...
    def doSetTextCursor(self, cursor: PySide6.QtGui.QTextCursor) -> None: ...
    def document(self) -> PySide6.QtGui.QTextDocument: ...
    def documentTitle(self) -> str: ...
    def dragEnterEvent(self, e: PySide6.QtGui.QDragEnterEvent) -> None: ...
    def dragLeaveEvent(self, e: PySide6.QtGui.QDragLeaveEvent) -> None: ...
    def dragMoveEvent(self, e: PySide6.QtGui.QDragMoveEvent) -> None: ...
    def dropEvent(self, e: PySide6.QtGui.QDropEvent) -> None: ...
    def ensureCursorVisible(self) -> None: ...
    def event(self, e: PySide6.QtCore.QEvent) -> bool: ...
    def extraSelections(self) -> List[PySide6.QtWidgets.QTextEdit.ExtraSelection]: ...
    @overload
    def find(
        self, exp: str, options: PySide6.QtGui.QTextDocument.FindFlag = ...
    ) -> bool: ...
    @overload
    def find(
        self,
        exp: Union[PySide6.QtCore.QRegularExpression, str],
        options: PySide6.QtGui.QTextDocument.FindFlag = ...,
    ) -> bool: ...
    def focusInEvent(self, e: PySide6.QtGui.QFocusEvent) -> None: ...
    def focusNextPrevChild(self, next: bool) -> bool: ...
    def focusOutEvent(self, e: PySide6.QtGui.QFocusEvent) -> None: ...
    def fontFamily(self) -> str: ...
    def fontItalic(self) -> bool: ...
    def fontPointSize(self) -> float: ...
    def fontUnderline(self) -> bool: ...
    def fontWeight(self) -> int: ...
    def inputMethodEvent(self, arg__1: PySide6.QtGui.QInputMethodEvent) -> None: ...
    @overload
    def inputMethodQuery(self, property: PySide6.QtCore.Qt.InputMethodQuery) -> Any: ...
    @overload
    def inputMethodQuery(
        self, query: PySide6.QtCore.Qt.InputMethodQuery, argument: Any
    ) -> Any: ...
    def insertFromMimeData(self, source: PySide6.QtCore.QMimeData) -> None: ...
    def insertHtml(self, text: str) -> None: ...
    def insertPlainText(self, text: str) -> None: ...
    def isReadOnly(self) -> bool: ...
    def isUndoRedoEnabled(self) -> bool: ...
    def keyPressEvent(self, e: PySide6.QtGui.QKeyEvent) -> None: ...
    def keyReleaseEvent(self, e: PySide6.QtGui.QKeyEvent) -> None: ...
    def lineWrapColumnOrWidth(self) -> int: ...
    def lineWrapMode(self) -> PySide6.QtWidgets.QTextEdit.LineWrapMode: ...
    def loadResource(self, type: int, name: Union[PySide6.QtCore.QUrl, str]) -> Any: ...
    def mergeCurrentCharFormat(
        self, modifier: PySide6.QtGui.QTextCharFormat
    ) -> None: ...
    def mouseDoubleClickEvent(self, e: PySide6.QtGui.QMouseEvent) -> None: ...
    def mouseMoveEvent(self, e: PySide6.QtGui.QMouseEvent) -> None: ...
    def mousePressEvent(self, e: PySide6.QtGui.QMouseEvent) -> None: ...
    def mouseReleaseEvent(self, e: PySide6.QtGui.QMouseEvent) -> None: ...
    def moveCursor(
        self,
        operation: PySide6.QtGui.QTextCursor.MoveOperation,
        mode: PySide6.QtGui.QTextCursor.MoveMode = ...,
    ) -> None: ...
    def overwriteMode(self) -> bool: ...
    def paintEvent(self, e: PySide6.QtGui.QPaintEvent) -> None: ...
    def paste(self) -> None: ...
    def placeholderText(self) -> str: ...
    def print_(self, printer: PySide6.QtGui.QPagedPaintDevice) -> None: ...
    def redo(self) -> None: ...
    def resizeEvent(self, e: PySide6.QtGui.QResizeEvent) -> None: ...
    def scrollContentsBy(self, dx: int, dy: int) -> None: ...
    def scrollToAnchor(self, name: str) -> None: ...
    def selectAll(self) -> None: ...
    def setAcceptRichText(self, accept: bool) -> None: ...
    def setAlignment(self, a: PySide6.QtCore.Qt.AlignmentFlag) -> None: ...
    def setAutoFormatting(
        self, features: PySide6.QtWidgets.QTextEdit.AutoFormattingFlag
    ) -> None: ...
    def setCurrentCharFormat(self, format: PySide6.QtGui.QTextCharFormat) -> None: ...
    def setCurrentFont(
        self, f: Union[PySide6.QtGui.QFont, str, Sequence[str]]
    ) -> None: ...
    def setCursorWidth(self, width: int) -> None: ...
    def setDocument(self, document: PySide6.QtGui.QTextDocument) -> None: ...
    def setDocumentTitle(self, title: str) -> None: ...
    def setExtraSelections(
        self, selections: Sequence[PySide6.QtWidgets.QTextEdit.ExtraSelection]
    ) -> None: ...
    def setFontFamily(self, fontFamily: str) -> None: ...
    def setFontItalic(self, b: bool) -> None: ...
    def setFontPointSize(self, s: float) -> None: ...
    def setFontUnderline(self, b: bool) -> None: ...
    def setFontWeight(self, w: int) -> None: ...
    def setHtml(self, text: str) -> None: ...
    def setLineWrapColumnOrWidth(self, w: int) -> None: ...
    def setLineWrapMode(
        self, mode: PySide6.QtWidgets.QTextEdit.LineWrapMode
    ) -> None: ...
    def setMarkdown(self, markdown: str) -> None: ...
    def setOverwriteMode(self, overwrite: bool) -> None: ...
    def setPlaceholderText(self, placeholderText: str) -> None: ...
    def setPlainText(self, text: str) -> None: ...
    def setReadOnly(self, ro: bool) -> None: ...
    def setTabChangesFocus(self, b: bool) -> None: ...
    def setTabStopDistance(self, distance: float) -> None: ...
    def setText(self, text: str) -> None: ...
    def setTextBackgroundColor(
        self,
        c: Union[
            PySide6.QtGui.QColor,
            PySide6.QtGui.QRgba64,
            Any,
            PySide6.QtCore.Qt.GlobalColor,
            str,
            int,
        ],
    ) -> None: ...
    def setTextColor(
        self,
        c: Union[
            PySide6.QtGui.QColor,
            PySide6.QtGui.QRgba64,
            Any,
            PySide6.QtCore.Qt.GlobalColor,
            str,
            int,
        ],
    ) -> None: ...
    def setTextCursor(self, cursor: PySide6.QtGui.QTextCursor) -> None: ...
    def setTextInteractionFlags(
        self, flags: PySide6.QtCore.Qt.TextInteractionFlag
    ) -> None: ...
    def setUndoRedoEnabled(self, enable: bool) -> None: ...
    def setWordWrapMode(self, policy: PySide6.QtGui.QTextOption.WrapMode) -> None: ...
    def showEvent(self, arg__1: PySide6.QtGui.QShowEvent) -> None: ...
    def tabChangesFocus(self) -> bool: ...
    def tabStopDistance(self) -> float: ...
    def textBackgroundColor(self) -> PySide6.QtGui.QColor: ...
    def textColor(self) -> PySide6.QtGui.QColor: ...
    def textCursor(self) -> PySide6.QtGui.QTextCursor: ...
    def textInteractionFlags(self) -> PySide6.QtCore.Qt.TextInteractionFlag: ...
    def timerEvent(self, e: PySide6.QtCore.QTimerEvent) -> None: ...
    def toHtml(self) -> str: ...
    def toMarkdown(
        self, features: PySide6.QtGui.QTextDocument.MarkdownFeature = ...
    ) -> str: ...
    def toPlainText(self) -> str: ...
    def undo(self) -> None: ...
    def wheelEvent(self, e: PySide6.QtGui.QWheelEvent) -> None: ...
    def wordWrapMode(self) -> PySide6.QtGui.QTextOption.WrapMode: ...
    def zoomIn(self, range: int = ...) -> None: ...
    def zoomInF(self, range: float) -> None: ...
    def zoomOut(self, range: int = ...) -> None: ...


class QCheckBox:
    """
    ![](assets/checkbox.png)

    A QCheckBox widget is a toggle button that can be checked or unchecked.
    Checkboxes are typically used to represent features in an application that
    can be enabled or disabled without affecting others. By default, a checkbox
    is unchecked.

    Examples:
        ``` py
        checkbox = QCheckBox()
        print(checkbox.isChecked())
        ```
        ```False```
        ``` py
        checkbox.setChecked(True)
        print(checkbox.isChecked())
        ```
        ```True```
    """

    def IsChecked() -> bool:
        """
        Returns True if the checkbox is checked; otherwise returns False.

        Returns:
            True if the checkbox is checked; otherwise False.
        """
        ...

    def setChecked(checked: bool):
        """
        Sets the checkbox to be checked if checked is True; otherwise sets it
        to be unchecked.

        Args:
            checked (bool): True to check the checkbox; otherwise False.
        """

    # stateChanged             : ClassVar[Signal] = ... # stateChanged(int)

    # @overload
    # def __init__(self, parent: Optional[PySide6.QtWidgets.QWidget] = ...) -> None: ...
    # @overload
    # def __init__(self, text: str, parent: Optional[PySide6.QtWidgets.QWidget] = ...) -> None: ...

    # def checkState(self) -> PySide6.QtCore.Qt.CheckState: ...
    # def checkStateSet(self) -> None: ...
    # def event(self, e: PySide6.QtCore.QEvent) -> bool: ...
    # def hitButton(self, pos: PySide6.QtCore.QPoint) -> bool: ...
    # def initStyleOption(self, option: PySide6.QtWidgets.QStyleOptionButton) -> None: ...
    # def isTristate(self) -> bool: ...
    # def minimumSizeHint(self) -> PySide6.QtCore.QSize: ...
    # def mouseMoveEvent(self, arg__1: PySide6.QtGui.QMouseEvent) -> None: ...
    # def nextCheckState(self) -> None: ...
    # def paintEvent(self, arg__1: PySide6.QtGui.QPaintEvent) -> None: ...
    # def setCheckState(self, state: PySide6.QtCore.Qt.CheckState) -> None: ...
    # def setTristate(self, y: bool = ...) -> None: ...
    # def sizeHint(self) -> PySide6.QtCore.QSize: ...


class QLabel:
    """
    ![](assets/label.png)

    QLabel is used for displaying text or an image. No user interaction
    functionality is provided.

    Examples:
        ``` py
        label = QLabel()
        label.setText("Hello World!")
        print(label.text())
        ```
        ```'Hello World!'```
    """

    # linkActivated            : ClassVar[Signal] = ... # linkActivated(QString)
    # linkHovered              : ClassVar[Signal] = ... # linkHovered(QString)

    # @overload
    # def __init__(self, parent: Optional[PySide6.QtWidgets.QWidget] = ..., f: PySide6.QtCore.Qt.WindowType = ...) -> None: ...
    # @overload
    # def __init__(self, text: str, parent: Optional[PySide6.QtWidgets.QWidget] = ..., f: PySide6.QtCore.Qt.WindowType = ...) -> None: ...

    # def alignment(self) -> PySide6.QtCore.Qt.AlignmentFlag: ...
    # def buddy(self) -> PySide6.QtWidgets.QWidget: ...
    # def changeEvent(self, arg__1: PySide6.QtCore.QEvent) -> None: ...
    # def clear(self) -> None: ...
    # def contextMenuEvent(self, ev: PySide6.QtGui.QContextMenuEvent) -> None: ...
    # def event(self, e: PySide6.QtCore.QEvent) -> bool: ...
    # def focusInEvent(self, ev: PySide6.QtGui.QFocusEvent) -> None: ...
    # def focusNextPrevChild(self, next: bool) -> bool: ...
    # def focusOutEvent(self, ev: PySide6.QtGui.QFocusEvent) -> None: ...
    # def hasScaledContents(self) -> bool: ...
    # def hasSelectedText(self) -> bool: ...
    # def heightForWidth(self, arg__1: int) -> int: ...
    # def indent(self) -> int: ...
    # def keyPressEvent(self, ev: PySide6.QtGui.QKeyEvent) -> None: ...
    # def margin(self) -> int: ...
    # def minimumSizeHint(self) -> PySide6.QtCore.QSize: ...
    # def mouseMoveEvent(self, ev: PySide6.QtGui.QMouseEvent) -> None: ...
    # def mousePressEvent(self, ev: PySide6.QtGui.QMouseEvent) -> None: ...
    # def mouseReleaseEvent(self, ev: PySide6.QtGui.QMouseEvent) -> None: ...
    # def movie(self) -> PySide6.QtGui.QMovie: ...
    # def openExternalLinks(self) -> bool: ...
    # def paintEvent(self, arg__1: PySide6.QtGui.QPaintEvent) -> None: ...
    # def picture(self) -> PySide6.QtGui.QPicture: ...
    # def pixmap(self) -> PySide6.QtGui.QPixmap: ...
    # def selectedText(self) -> str: ...
    # def selectionStart(self) -> int: ...
    # def setAlignment(self, arg__1: PySide6.QtCore.Qt.AlignmentFlag) -> None: ...
    # def setBuddy(self, arg__1: PySide6.QtWidgets.QWidget) -> None: ...
    # def setIndent(self, arg__1: int) -> None: ...
    # def setMargin(self, arg__1: int) -> None: ...
    # def setMovie(self, movie: PySide6.QtGui.QMovie) -> None: ...
    # @overload
    # def setNum(self, arg__1: float) -> None: ...
    # @overload
    # def setNum(self, arg__1: int) -> None: ...
    # def setOpenExternalLinks(self, open: bool) -> None: ...
    # def setPicture(self, arg__1: Union[PySide6.QtGui.QPicture, int]) -> None: ...
    # def setPixmap(self, arg__1: Union[PySide6.QtGui.QPixmap, PySide6.QtGui.QImage, str]) -> None: ...
    # def setScaledContents(self, arg__1: bool) -> None: ...
    # def setSelection(self, arg__1: int, arg__2: int) -> None: ...
    def setText(self, text: str) -> None:
        """
        Sets the label's text to the given text.

        Args:
            text (str): The text to set.
        """

    # def setTextFormat(self, arg__1: PySide6.QtCore.Qt.TextFormat) -> None: ...
    # def setTextInteractionFlags(self, flags: PySide6.QtCore.Qt.TextInteractionFlag) -> None: ...
    # def setWordWrap(self, on: bool) -> None: ...
    # def sizeHint(self) -> PySide6.QtCore.QSize: ...
    def text(self) -> str:
        """
        Returns the label's text.

        Returns:
            The label's text.
        """

    # def textFormat(self) -> PySide6.QtCore.Qt.TextFormat: ...
    # def textInteractionFlags(self) -> PySide6.QtCore.Qt.TextInteractionFlag: ...
    # def wordWrap(self) -> bool: ...


class QComboBox:
    """
    ![](assets/combobox.png)

    A QComboBox is a button that provides a list of options to the user when clicked.

    Examples:
        ``` py
        combo = QComboBox()
        combo.addItem("Option 1")
        combo.addItems("[Option 2, Option 3]")
        print(combo.currentText())
        ```
        ```'Option 1'```
        ``` py
        print(combo.currentIndex())
        ```
        ```'0'```
        ``` py
        combo.setCurrentIndex(2)
        print(combo.currentText())
        ```
        ```'Option 3'```
        ``` py
        combo.clear()
        print(combo.currentText())
        ```
        ```''```
        ``` py
        print(combo.currentIndex())
        ```
        ```'-1'```
    """

    # activated                : ClassVar[Signal] = ... # activated(int)
    currentIndexChanged: ClassVar[Signal] = ...  # currentIndexChanged(int)
    # currentTextChanged       : ClassVar[Signal] = ... # currentTextChanged(QString)
    # editTextChanged          : ClassVar[Signal] = ... # editTextChanged(QString)
    # highlighted              : ClassVar[Signal] = ... # highlighted(int)
    # textActivated            : ClassVar[Signal] = ... # textActivated(QString)
    # textHighlighted          : ClassVar[Signal] = ... # textHighlighted(QString)

    # class InsertPolicy(enum.Enum):

    #     NoInsert: QComboBox.InsertPolicy = ...  # 0x0
    #     InsertAtTop: QComboBox.InsertPolicy = ...  # 0x1
    #     InsertAtCurrent: QComboBox.InsertPolicy = ...  # 0x2
    #     InsertAtBottom: QComboBox.InsertPolicy = ...  # 0x3
    #     InsertAfterCurrent: QComboBox.InsertPolicy = ...  # 0x4
    #     InsertBeforeCurrent: QComboBox.InsertPolicy = ...  # 0x5
    #     InsertAlphabetically: QComboBox.InsertPolicy = ...  # 0x6

    # class SizeAdjustPolicy(enum.Enum):

    #     AdjustToContents: QComboBox.SizeAdjustPolicy = ...  # 0x0
    #     AdjustToContentsOnFirstShow: QComboBox.SizeAdjustPolicy = ...  # 0x1
    #     AdjustToMinimumContentsLengthWithIcon: QComboBox.SizeAdjustPolicy = ...  # 0x2

    # def __init__(self, parent: Optional[PySide6.QtWidgets.QWidget] = ...) -> None: ...

    # @overload
    # def addItem(self,icon: Union[PySide6.QtGui.QIcon, PySide6.QtGui.QPixmap], text: str, userData: Any = ...,) -> None: ...
    # @overload
    def addItem(self, text: str) -> None:
        """
        Adds an item to the combo box with the given text.

        Args:
            text (str): The text to display in the combo box.
        """

    def addItems(self, texts: Sequence[str]) -> None:
        """
        Adds the items in the list texts to the combo box.

        Args:
            texts (Sequence[str]): The list of strings to add to the combo box.
        """

    # def changeEvent(self, e: PySide6.QtCore.QEvent) -> None: ...
    def clear(self) -> None:
        """
        Clears the contents of the combo box, removing all items.
        """

    # def clearEditText(self) -> None: ...
    # def completer(self) -> PySide6.QtWidgets.QCompleter: ...
    # def contextMenuEvent(self, e: PySide6.QtGui.QContextMenuEvent) -> None: ...
    # def count(self) -> int: ...
    # def currentData(self, role: int = ...) -> Any: ...
    def currentIndex(self) -> int:
        """
        Gets the index of the currently selected item in the combo box. For
        an empty combo box, returns -1. The current index can change when inserting
        or removing items.

        Returns:
            The index of the currently selected item.
        """

    def currentText(self) -> str:
        """
        Gets the text of the currently selected item in the combo box. For an
        empty combo box, returns an empty string.

        Returns:
            The text of the currently selected item.
        """

    # def duplicatesEnabled(self) -> bool: ...
    # def event(self, event: PySide6.QtCore.QEvent) -> bool: ...
    # def findData(self, data: Any, role: int = ..., flags: PySide6.QtCore.Qt.MatchFlag = ...) -> int: ...
    # def findText(self, text: str, flags: PySide6.QtCore.Qt.MatchFlag = ...) -> int: ...
    # def focusInEvent(self, e: PySide6.QtGui.QFocusEvent) -> None: ...
    # def focusOutEvent(self, e: PySide6.QtGui.QFocusEvent) -> None: ...
    # def hasFrame(self) -> bool: ...
    # def hideEvent(self, e: PySide6.QtGui.QHideEvent) -> None: ...
    # def hidePopup(self) -> None: ...
    # def iconSize(self) -> PySide6.QtCore.QSize: ...
    # def initStyleOption(self, option: PySide6.QtWidgets.QStyleOptionComboBox) -> None: ...
    # def inputMethodEvent(self, arg__1: PySide6.QtGui.QInputMethodEvent) -> None: ...
    # @overload
    # def inputMethodQuery(self, arg__1: PySide6.QtCore.Qt.InputMethodQuery) -> Any: ...
    # @overload
    # def inputMethodQuery(self, query: PySide6.QtCore.Qt.InputMethodQuery, argument: Any) -> Any: ...
    # @overload
    # def insertItem(self, index: int, icon: Union[PySide6.QtGui.QIcon, PySide6.QtGui.QPixmap], text: str, userData: Any = ...) -> None: ...
    # @overload
    # def insertItem(self, index: int, text: str, userData: Any = ...) -> None: ...
    # def insertItems(self, index: int, texts: Sequence[str]) -> None: ...
    # def insertPolicy(self) -> PySide6.QtWidgets.QComboBox.InsertPolicy: ...
    # def insertSeparator(self, index: int) -> None: ...
    # def isEditable(self) -> bool: ...
    # def itemData(self, index: int, role: int = ...) -> Any: ...
    # def itemDelegate(self) -> PySide6.QtWidgets.QAbstractItemDelegate: ...
    # def itemIcon(self, index: int) -> PySide6.QtGui.QIcon: ...
    # def itemText(self, index: int) -> str: ...
    # def keyPressEvent(self, e: PySide6.QtGui.QKeyEvent) -> None: ...
    # def keyReleaseEvent(self, e: PySide6.QtGui.QKeyEvent) -> None: ...
    # def lineEdit(self) -> PySide6.QtWidgets.QLineEdit: ...
    # def maxCount(self) -> int: ...
    # def maxVisibleItems(self) -> int: ...
    # def minimumContentsLength(self) -> int: ...
    # def minimumSizeHint(self) -> PySide6.QtCore.QSize: ...
    # def model(self) -> PySide6.QtCore.QAbstractItemModel: ...
    # def modelColumn(self) -> int: ...
    # def mousePressEvent(self, e: PySide6.QtGui.QMouseEvent) -> None: ...
    # def mouseReleaseEvent(self, e: PySide6.QtGui.QMouseEvent) -> None: ...
    # def paintEvent(self, e: PySide6.QtGui.QPaintEvent) -> None: ...
    # def placeholderText(self) -> str: ...
    def removeItem(self, index: int) -> None:
        """
        Removes the item at the given index from the combo box.

        Args:
            index (int): The index of the item to remove.
        """

    # def resizeEvent(self, e: PySide6.QtGui.QResizeEvent) -> None: ...
    # def rootModelIndex(self) -> PySide6.QtCore.QModelIndex: ...
    # def setCompleter(self, c: PySide6.QtWidgets.QCompleter) -> None: ...
    def setCurrentIndex(self, index: int) -> None:
        """
        Sets the current index of the combo box to the given index.

        Args:
            index (int): The index of the item to set as the current item.
        """

    def setCurrentText(self, text: str) -> None:
        """
        Sets the current text of the combo box to the given text.

        Args:
            text (str): The text to set as the current text.
        """

    # def setText(): ...

    # def setDuplicatesEnabled(self, enable: bool) -> None: ...
    # def setEditText(self, text: str) -> None: ...
    # def setEditable(self, editable: bool) -> None: ...
    # def setFrame(self, arg__1: bool) -> None: ...
    # def setIconSize(self, size: PySide6.QtCore.QSize) -> None: ...
    # def setInsertPolicy(self, policy: PySide6.QtWidgets.QComboBox.InsertPolicy) -> None: ...
    # def setItemData(self, index: int, value: Any, role: int = ...) -> None: ...
    # def setItemDelegate(self, delegate: PySide6.QtWidgets.QAbstractItemDelegate) -> None: ...
    # def setItemIcon(self, index: int, icon: Union[PySide6.QtGui.QIcon, PySide6.QtGui.QPixmap]) -> None: ...
    # def setItemText(self, index: int, text: str) -> None: ...
    # def setLineEdit(self, edit: PySide6.QtWidgets.QLineEdit) -> None: ...
    # def setMaxCount(self, max: int) -> None: ...
    # def setMaxVisibleItems(self, maxItems: int) -> None: ...
    # def setMinimumContentsLength(self, characters: int) -> None: ...
    # def setModel(self, model: PySide6.QtCore.QAbstractItemModel) -> None: ...
    # def setModelColumn(self, visibleColumn: int) -> None: ...
    # def setPlaceholderText(self, placeholderText: str) -> None: ...
    # def setRootModelIndex(self, index: Union[PySide6.QtCore.QModelIndex, PySide6.QtCore.QPersistentModelIndex]) -> None: ...
    # def setSizeAdjustPolicy(self, policy: PySide6.QtWidgets.QComboBox.SizeAdjustPolicy) -> None: ...
    # def setValidator(self, v: PySide6.QtGui.QValidator) -> None: ...
    # def setView(self, itemView: PySide6.QtWidgets.QAbstractItemView) -> None: ...
    # def showEvent(self, e: PySide6.QtGui.QShowEvent) -> None: ...
    # def showPopup(self) -> None: ...
    # def sizeAdjustPolicy(self) -> PySide6.QtWidgets.QComboBox.SizeAdjustPolicy: ...
    # def sizeHint(self) -> PySide6.QtCore.QSize: ...
    # def validator(self) -> PySide6.QtGui.QValidator: ...
    # def view(self) -> PySide6.QtWidgets.QAbstractItemView: ...
    # def wheelEvent(self, e: PySide6.QtGui.QWheelEvent) -> None: ...


class QSpinBox:
    """
    ![](assets/spinbox.png)

    QSpinBox is designed to handle integers and discrete sets of values. Use
    QDoubleSpinBox for floating point values. QSpinBox allows the user to choose
    a value by clicking the up and down buttons to increment or decrement the
    value displayed. The value can also be changed by typing in a value. The range
    of valid values and the number of decimal places shown is configurable.

    Examples:
        ``` py
        spin_box = QSpinBox()
        spin_box.setMaximum(100)
        spin_box.setMinimum(0)
        spin_box.setSingleStep(5)
        spin_box.setValue(50)
        print(spin_box.value())
        ```
        ```50```
        ``` py
        spin_box.setValue(200)
        print(spin_box.value())
        ```
        ```100```
    """

    textChanged: ClassVar[Signal] = ...  # textChanged(QString)
    valueChanged: ClassVar[Signal] = ...  # valueChanged(int)

    # def __init__(self, parent: Optional[PySide6.QtWidgets.QWidget] = ...) -> None: ...

    # def cleanText(self) -> str: ...
    # def displayIntegerBase(self) -> int: ...
    # def event(self, event: PySide6.QtCore.QEvent) -> bool: ...
    # def fixup(self, str: str) -> str: ...
    # def maximum(self) -> int: ...
    # def minimum(self) -> int: ...
    # def prefix(self) -> str: ...
    # def setDisplayIntegerBase(self, base: int) -> None: ...

    def setMaximum(self, max: int) -> None:
        """
        Sets the maximum value of the spin box. The default maximum value is 99.

        Args:
            max (int): The maximum value of the spin box.
        """

    def setMinimum(self, min: int) -> None:
        """
        Sets the minimum value of the spin box. The default minimum value
        is 0.

        Args:
            min (int): The minimum value of the spin box.
        """

    # def setPrefix(self, prefix: str) -> None: ...
    # def setRange(self, min: int, max: int) -> None: ...

    def setSingleStep(self, val: int) -> None:
        """
        Sets the value that the spin box will increment or decrement by when the
        up or down buttons are clicked. The default step value is 1. Setting a
        value less than 0 does nothing.

        Args:
            val (int): The value to increment or decrement by.
        """

    # def setStepType(self, stepType: PySide6.QtWidgets.QAbstractSpinBox.StepType) -> None: ...
    # def setSuffix(self, suffix: str) -> None: ...
    def setValue(self, val: int) -> None:
        """
        Sets the value of the spin box. If the value is outside the range of
        the spin box, the value is adjusted to the nearest limit.

        Args:
            val (int): The value to set the spin box to.
        """

    # def singleStep(self) -> int: ...
    # def stepType(self) -> PySide6.QtWidgets.QAbstractSpinBox.StepType: ...
    # def suffix(self) -> str: ...
    # def textFromValue(self, val: int) -> str: ...
    # def validate(self, input: str, pos: int) -> object: ...
    def value(self) -> int:
        """
        Returns the current value of the spin box.

        Returns:
            The current value of the spin box.
        """

    # def valueFromText(self, text: str) -> int: ...


class QDoubleSpinBox:
    """
    ![](assets/double_spinbox.png)

    QDoubleSpinBox is designed to handle double values. For integers, use QSpinBox.
    QDoubleSpinBox allows the user to choose a value by clicking the up and down
    buttons to increment or decrement the value displayed. The value can also be
    changed by typing in a value. The range of valid values and the number of
    decimal places shown is configurable.

    Examples:
        ``` py
        spin_box = QDoubleSpinBox()
        spin_box.setMaximum(100)
        spin_box.setMinimum(0)
        spin_box.setSingleStep(0.1)
        spin_box.setValue(50)
        print(spin_box.value())
        ```
        ```50.0```
        ``` py
        spin_box.setValue(200)
        print(spin_box.value())
        ```
        ```100.0```
    """

    textChanged: ClassVar[Signal] = ...  # textChanged(QString)
    valueChanged: ClassVar[Signal] = ...  # valueChanged(double)

    # def __init__(self, parent: Optional[PySide6.QtWidgets.QWidget] = ...) -> None: ...

    # def cleanText(self) -> str: ...
    # def decimals(self) -> int: ...
    # def fixup(self, str: str) -> str: ...
    # def maximum(self) -> float: ...
    # def minimum(self) -> float: ...
    # def prefix(self) -> str: ...
    # def setDecimals(self, prec: int) -> None: ...
    def setMaximum(self, max: float) -> None:
        """
        Sets the maximum value of the spin box. The default maximum value
        is 99.99.

        Args:
            max: The new maximum value.
        """

    def setMinimum(self, min: float) -> None:
        """
        Sets the minimum value of the spin box. The default minimum value
        is 0.0.

        Args:
            min: The new minimum value.
        """

    # def setPrefix(self, prefix: str) -> None: ...
    # def setRange(self, min: float, max: float) -> None: ...
    def setSingleStep(self, val: float) -> None:
        """
        Sets the value that the spin box will increment or decrement by when the
        up or down buttons are clicked. The default step value is 1.0. Setting a
        singleStep value of less than 0 does nothing.

        Args:
            val: The new step value.
        """

    # def setStepType(self, stepType: PySide6.QtWidgets.QAbstractSpinBox.StepType) -> None: ...
    # def setSuffix(self, suffix: str) -> None: ...
    def setValue(self, val: float) -> None:
        """
        Sets the value of the spin box. If the value is outside the range of the
        spin box, the value is adjusted to the nearest limit.

        Args:
            val: The new value.
        """

    # def singleStep(self) -> float: ...
    # def stepType(self) -> PySide6.QtWidgets.QAbstractSpinBox.StepType: ...
    # def suffix(self) -> str: ...
    # def textFromValue(self, val: float) -> str: ...
    # def validate(self, input: str, pos: int) -> object: ...
    def value(self) -> float:
        """
        Returns the value of the spin box.

        Returns:
            The value of the spin box.
        """

    # def valueFromText(self, text: str) -> float: ...


class QPushButton:
    """
    ![](assets/pushbutton.png)

    The push button, or command button, is perhaps the most commonly used widget
    in any graphical user interface. Push (click) a button to command the computer
    to perform some action, or to answer a question. Typical buttons are OK, Apply,
    Cancel, Close, Yes, No and Help.

    Examples:
        ``` py
        button = QPushButton()
        button.setText("Click me!")
        print(button.text())
        ```
        ```'Click me!'```
    """

    clicked: ClassVar[Signal] = ...  # clicked()

    def text(self) -> str:
        """
        Returns the text displayed in the button.

        Returns:
            The text displayed in the button.
        """

    def setText(text: str) -> None:
        """
        Sets the text to be displayed in the button.

        Args:
            text (str): The text to display in the button.
        """

    # @overload
    # def __init__(self, icon: Union[PySide6.QtGui.QIcon, PySide6.QtGui.QPixmap], text: str, parent: Optional[PySide6.QtWidgets.QWidget] = ...) -> None: ...
    # @overload
    # def __init__(self, parent: Optional[PySide6.QtWidgets.QWidget] = ...) -> None: ...
    # @overload
    # def __init__(self, text: str, parent: Optional[PySide6.QtWidgets.QWidget] = ...) -> None: ...

    # def autoDefault(self) -> bool: ...
    # def event(self, e: PySide6.QtCore.QEvent) -> bool: ...
    # def focusInEvent(self, arg__1: PySide6.QtGui.QFocusEvent) -> None: ...
    # def focusOutEvent(self, arg__1: PySide6.QtGui.QFocusEvent) -> None: ...
    # def hitButton(self, pos: PySide6.QtCore.QPoint) -> bool: ...
    # def initStyleOption(self, option: PySide6.QtWidgets.QStyleOptionButton) -> None: ...
    # def isDefault(self) -> bool: ...
    # def isFlat(self) -> bool: ...
    # def keyPressEvent(self, arg__1: PySide6.QtGui.QKeyEvent) -> None: ...
    # def menu(self) -> PySide6.QtWidgets.QMenu: ...
    # def minimumSizeHint(self) -> PySide6.QtCore.QSize: ...
    # def mouseMoveEvent(self, arg__1: PySide6.QtGui.QMouseEvent) -> None: ...
    # def paintEvent(self, arg__1: PySide6.QtGui.QPaintEvent) -> None: ...
    # def setAutoDefault(self, arg__1: bool) -> None: ...
    # def setDefault(self, arg__1: bool) -> None: ...
    # def setFlat(self, arg__1: bool) -> None: ...
    # def setMenu(self, menu: PySide6.QtWidgets.QMenu) -> None: ...
    # def showMenu(self) -> None: ...
    # def sizeHint(self) -> PySide6.QtCore.QSize: ...
